version: '3.2'
volumes:
  grafana_data: {}
  prometheus_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --storage.tsdb.path=/prometheus
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus_data
        target: /prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - type: bind
        source: ./grafana/provisioning/
        target: /etc/grafana/provisioning/
      - type: bind
        source: ./grafana/dashboards/
        target: /var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
    env_file:
      - ./grafana/grafana.config
    ports:
      - 3000:3000
  aleph_exporter:
      image: ckluenter/alephexporter:latest
      container_name: alephexporter
      ports:
        - "8080:8080"
      env_file:
        - aleph-exporter.env

