name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12' # The Go version to download (if necessary) and use.
    - name: test
      run: make test
    - name: docker-build
      run: make docker
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ckluenter/alephexporter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

